### Register
POST http://localhost:8000/api/v1/auth/register/
Content-Type: application/json

{
    "email": "jordan@gmail.com",
    "password": "admin123",
}

### Login
POST http://localhost:8000/api/v1/auth/login/
Content-Type: application/json

{
    "email": "jordanmaulana25@gmail.com",
    "password": "admin123"
}

### Forgot Password
POST http://localhost:8000/api/v1/auth/forgot-password/
Content-Type: application/json

{
    "email": "jordanmaulana25@gmail.com"
}