# Generated by Django 5.2.1 on 2025-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="area",
            field=models.CharField(
                choices=[
                    ("SE_ASIA", "SE Asia"),
                    ("EMEA", "EMEA"),
                    ("APAC", "APAC"),
                    ("EU", "EU"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="availability_type",
            field=models.CharField(
                choices=[
                    ("REMOTE", "Remote"),
                    ("ONSITE", "Onsite"),
                    ("HYBRID", "Hybrid"),
                ],
                default="REMOTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile",
            field=models.TextField(blank=True, null=True),
        ),
    ]
