# Generated by Django 5.2.1 on 2025-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_area_profile_availability_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hard_skill_gaps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="soft_skill_gaps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
