# Generated by Django 5.2.1 on 2025-09-10 12:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_hard_skill_gaps_profile_soft_skill_gaps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="area",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="availability_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin_url",
        ),
        migrations.CreateModel(
            name="ProfilePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=core.models.make_object_id, max_length=32
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("ONSITE", "Onsite"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="REMOTE",
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-uid"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_on"], name="profiles_pr_created_4eb719_idx"
                    )
                ],
            },
        ),
    ]
