services:
  web:
    build: .
    container_name: api.cariinkerja.id
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-cariinkerja}

  db:
    image: postgres:15-alpine
    container_name: postgres.cariinkerja.id
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cariinkerja}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
  default:
    external:
      name: n8n_default
