# Generated by Django 5.2.1 on 2025-09-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0003_profile_hard_skill_gaps_profile_soft_skill_gaps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=core.models.make_object_id, max_length=32
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("link", models.URLField(unique=True)),
                ("hard_skills", models.TextField(blank=True, null=True)),
                ("soft_skills", models.TextField(blank=True, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uid"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True, default=core.models.make_object_id, max_length=32
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField()),
                ("hard_skill_gap", models.TextField()),
                ("soft_skill_gap", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.jobs"
                    ),
                ),
            ],
            options={
                "ordering": ["-uid"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="jobs",
            index=models.Index(
                fields=["created_on"], name="jobs_jobs_created_6b7968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobassessment",
            index=models.Index(
                fields=["created_on"], name="jobs_jobass_created_854209_idx"
            ),
        ),
    ]
