# Generated by Django 5.2.1 on 2025-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                ],
                default="full_time",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="job_title_category",
            field=models.CharField(default="other", max_length=255),
        ),
        migrations.AddField(
            model_name="jobs",
            name="work_location",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("onsite", "Onsite"),
                    ("hybrid", "Hybrid"),
                ],
                default="remote",
                max_length=255,
            ),
        ),
    ]
