# Generated by Django 5.2.1 on 2025-09-06 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobs_employment_type_jobs_job_title_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="posted_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
