# Generated by Django 5.2.1 on 2025-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobs_posted_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobassessment",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
