# Generated by Django 5.2.1 on 2025-09-06 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobassessment_hard_skill_gap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="requirements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
    ]
