# Generated by Django 5.2.1 on 2025-09-06 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_jobs_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobassessment",
            name="hard_skill_gap",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobassessment",
            name="soft_skill_gap",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="hard_skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="soft_skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
    ]
