# Generated by Django 5.2.1 on 2025-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_jobassessment_hard_skill_gap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
