# Generated by Django 5.2.1 on 2025-09-06 23:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobs_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="requirements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=800),
                blank=True,
                default=list,
                null=True,
                size=20,
            ),
        ),
    ]
