# Generated by Django 5.2.1 on 2025-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_jobs_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="source_platform",
            field=models.CharField(default="weworkremotely.com", max_length=255),
        ),
    ]
