# Generated by Django 5.2.1 on 2025-09-09 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_jobs_source_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="posted_on",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
