# Generated by Django 5.2.1 on 2025-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_jobs_posted_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="source_platform",
            field=models.CharField(
                choices=[
                    ("weworkremotely.com", "WeWorkRemotely"),
                    ("indeed.com", "Indeed"),
                ],
                default="weworkremotely.com",
                max_length=255,
            ),
        ),
    ]
